# Generated by Django 5.1.6 on 2025-02-21 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("city", models.CharField(max_length=300)),
                ("country", models.CharField(max_length=300)),
                ("createdAt", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="WaterBottle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=3)),
                ("brand", models.CharField(max_length=300)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=7)),
                ("size", models.CharField(max_length=5)),
                ("mouthSize", models.CharField(max_length=14)),
                ("color", models.CharField(max_length=11)),
                ("currentQuantity", models.PositiveSmallIntegerField()),
                (
                    "suppliedBy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MyInventoryApp.supplier",
                    ),
                ),
            ],
        ),
    ]
